### ISSUE TITLE
Text content not being updated

### ISSUE THREAD

**Issue by low-earth-orbit** [low-earth-orbit/konva-whiteboard#60]
**Describe the bug**
Text content not been updated in local storage. The text property of the text object in canvasState is not updated with updated text value.

**To Reproduce**

1. Add text
2. Update text content
3. Refresh the page
4. Text content remains the default one

**Expected behavior**
Text content should remain the same before vs after refreshing the page.

**Comment by zaheer-Khan3260** [comment]
Hey, can you assign to me i can fix this issue.

**Comment by low-earth-orbit** [comment]
@zaheer-Khan3260 Assigned. Let me know if you have questions / want more information.

**Comment by low-earth-orbit** [comment]
@zaheer-Khan3260 I just unassigned you from this issue.
